author: tocfoundation.org
description: tocfoundation.org, to protect our kids, we have to fight with evil.
keyword: 金橙公益基金会 
favicon: 

excerpt_link: Read more

menu:
 "WHO WE ARE": /who-we-are/
 "WHAT WE DO": /what-we-do/
 "WHAT'S NEW": /blog/
 "GET INVOLVED": /get-involved/
 "CONTACT": /contact/

# highlight
highlight:
  tomorrow

# catalog
catalog: false

# donate
donate: false

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: disqus

# gitment config
# gitment_owner: yanm1ng
# gitment_repo: yanm1ng.github.io
# gitment_oauth_id: 0f87e490e00ee3fd87ef
# gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 

google_analytics:
  enabled: true
  id: UA-141207496-1

# disqus config
disqus_shortname: fightingasparents

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://24dlmn2bqamt1e72kah59881-wpengine.netdna-ssl.com/wp-content/uploads/2016/02/boxing-gloves-fighting-chargebacks.jpg
  description: "To protect my kids, i have to fight with the evil.<br><br><br> <small>contact with fightingasparents#gmail(dot)com</small>"
  weibo_username: 
  twitter_username: 
  github_username: 
  zhihu_username: 
  douban_username: 
  linkedin_username:

# MathJax Support
mathjax:
  enable: false
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
all_minifier: false
